all: Program.cpp most.cpp longest.cpp happiest.cpp
	g++ -o most Program.cpp most.cpp -O2
	g++ -o longest Program.cpp longest.cpp -O2
	g++ -o happiest Program.cpp happiest.cpp -O2

most: Program.cpp most.cpp
	g++ -o most Program.cpp most.cpp -O2

longest: Program.cpp longest.cpp
	g++ -o longest Program.cpp longest.cpp -O2

happiest: Program.cpp happiest.cpp
	g++ -o happiest Program.cpp happiest.cpp -O2

clear: 
	rm most.exe longest.exe happiest.exe 
